# Generated by Django 6.0.5 on 2026-05-29 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_alter_task_usuario_task_departamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='horas_estimadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Horas estimadas'),
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Comentario')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comentarios', to='core.task', verbose_name='Tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario de tarea',
                'verbose_name_plural': 'Comentarios de tareas',
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creada', 'Creada'), ('editada', 'Editada'), ('estado', 'Cambio de estado'), ('reasignada', 'Reasignada')], max_length=20, verbose_name='Acción')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.task', verbose_name='Tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de tarea',
                'verbose_name_plural': 'Historiales de tareas',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de plantilla')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de tarea')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad')),
                ('horas_estimadas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Horas estimadas')),
                ('recurrente', models.BooleanField(default=False, verbose_name='Recurrente')),
                ('frecuencia', models.CharField(blank=True, choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=10, verbose_name='Frecuencia')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Plantilla de tarea',
                'verbose_name_plural': 'Plantillas de tareas',
                'ordering': ['-creado'],
            },
        ),
    ]
