# Generated by Django 6.0.5 on 2026-05-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_icon',
            field=models.CharField(blank=True, choices=[('', 'Ninguno (inicial del nombre)'), ('🧑\u200d💻', 'Programador'), ('👨\u200d💻', 'Programador hombre'), ('👩\u200d💻', 'Programadora mujer'), ('🕵️', 'Detective'), ('🧑\u200d🔧', 'Técnico'), ('👨\u200d🔧', 'Técnico hombre'), ('👩\u200d🔧', 'Técnica mujer'), ('🧑\u200d🚀', 'Astronauta'), ('👨\u200d🚀', 'Astronauta hombre'), ('👩\u200d🚀', 'Astronauta mujer'), ('🧑\u200d🔬', 'Científico'), ('👨\u200d🔬', 'Científico hombre'), ('👩\u200d🔬', 'Científica mujer'), ('🧑\u200d🏫', 'Profesor'), ('👨\u200d🏫', 'Profesor hombre'), ('👩\u200d🏫', 'Profesora mujer'), ('🧑\u200d🎓', 'Estudiante'), ('👨\u200d🎓', 'Estudiante hombre'), ('👩\u200d🎓', 'Estudiante mujer'), ('🧑\u200d🎨', 'Artista'), ('👨\u200d🎨', 'Artista hombre'), ('👩\u200d🎨', 'Artista mujer'), ('🧑\u200d🍳', 'Cocinero'), ('👨\u200d🍳', 'Cocinero hombre'), ('👩\u200d🍳', 'Cocinera mujer'), ('🧑\u200d⚕️', 'Médico'), ('👨\u200d⚕️', 'Médico hombre'), ('👩\u200d⚕️', 'Médica mujer'), ('🧑\u200d✈️', 'Piloto'), ('👨\u200d✈️', 'Piloto hombre'), ('👩\u200d✈️', 'Piloto mujer'), ('🧑\u200d🌾', 'Granjero'), ('👨\u200d🌾', 'Granjero hombre'), ('👩\u200d🌾', 'Granjera mujer'), ('🦸', 'Superhéroe'), ('🦹', 'Supervillano'), ('🧙', 'Mago/Maga'), ('🧝', 'Elfo/Elfa'), ('🧛', 'Vampiro'), ('🧞', 'Genio'), ('🧜', 'Sireno/Sirena'), ('🎅', 'Santa Claus'), ('🤴', 'Príncipe'), ('👸', 'Princesa'), ('👑', 'Corona')], default='', max_length=20, verbose_name='Icono de perfil'),
        ),
    ]
