# Generated by Django 6.0.5 on 2026-05-29 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_avatar_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='departamentos',
            field=models.ManyToManyField(blank=True, related_name='perfiles', to='core.department', verbose_name='Departamentos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department', verbose_name='Departamento (principal)'),
        ),
    ]
