# Generated by Django 6.0.5 on 2026-05-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_departamentos_alter_profile_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Usuario')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('success', models.BooleanField(default=False, verbose_name='Exitoso')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Intento de login',
                'verbose_name_plural': 'Intentos de login',
                'ordering': ['-creado'],
            },
        ),
    ]
