# Generated by Django 6.0.5 on 2026-05-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_loginlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['orden', '-fecha_creacion', '-creado'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AddField(
            model_name='task',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='task',
            name='share_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Token compartir'),
        ),
    ]
