# Generated by Django 6.0.5 on 2026-06-01 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_task_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear_usuario', 'Crear usuario'), ('editar_usuario', 'Editar usuario'), ('eliminar_tarea', 'Eliminar tarea'), ('reasignar_masiva', 'Reasignación masiva'), ('cambiar_rol', 'Cambiar rol'), ('backup', 'Copia de seguridad'), ('otro', 'Otro')], max_length=30, verbose_name='Acción')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Bitácora de administración',
                'verbose_name_plural': 'Bitácoras de administración',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='Hash de contraseña')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de contraseña',
                'verbose_name_plural': 'Historial de contraseñas',
                'ordering': ['-creado'],
            },
        ),
    ]
