# Generated by Django 6.0.5 on 2026-06-01 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_adminlog_passwordhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bloqueada desde'),
        ),
        migrations.AddField(
            model_name='task',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_bloqueadas', to=settings.AUTH_USER_MODEL, verbose_name='Bloqueada por'),
        ),
        migrations.CreateModel(
            name='TaskWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observadores', to='core.task', verbose_name='Tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_observadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Observador de tarea',
                'verbose_name_plural': 'Observadores de tareas',
                'ordering': ['-creado'],
                'unique_together': {('usuario', 'tarea')},
            },
        ),
    ]
