# Generated by Django 6.0.5 on 2026-06-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_task_locked_at_task_locked_by_taskwatcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En Proceso'), ('revision', 'En Revisión'), ('terminada', 'Terminada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
