# Generated by Django 6.0.5 on 2026-06-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_task_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_backup', models.BooleanField(default=False, verbose_name='Copias automáticas')),
                ('interval_hours', models.PositiveIntegerField(default=24, verbose_name='Intervalo (horas)')),
                ('keep_last', models.PositiveIntegerField(default=10, verbose_name='Conservar últimas')),
                ('last_backup', models.DateTimeField(blank=True, null=True, verbose_name='Última copia')),
            ],
            options={
                'verbose_name': 'Configuración de respaldo',
                'verbose_name_plural': 'Configuración de respaldos',
            },
        ),
    ]
